## Setting Paths with Label from audio Dataset

### Import Libraries

In [3]:
import os
import pandas as pd

In [2]:
# Male dataset paths
male_aggressive_path = "Audio Dataset\\Male\\Aggressive"
male_non_aggressive_path = "Audio Dataset\\Male\\Non-Aggressive"
# Female dataset paths
female_aggressive_path = "Audio Dataset\\Female\\Aggressive"
female_non_aggressive_path = "Audio Dataset\\Female\\Non-Aggressive"

In [4]:
# Save the path to audio and their labels, gender in a dataframe

female_agg_dir_list = os.listdir(female_aggressive_path)
path = []
aggressiveness = []
gender = []
for i in female_agg_dir_list:
    path.append(female_aggressive_path + '\\' + i)
    aggressiveness.append(1)
    gender.append(0)

female_agg_df = pd.DataFrame({'path': path, 'aggressiveness': aggressiveness, 'gender':gender})
female_agg_df.head()

                                                path  aggressiveness  gender
0  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0
1  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0
2  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0
3  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0
4  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0

In [6]:
female_non_agg_dir_list = os.listdir(female_non_aggressive_path)
path = []
aggressiveness = []
gender = []
for i in female_non_agg_dir_list:
    path.append(female_non_aggressive_path + '\\' + i)
    aggressiveness.append(0)
    gender.append(0)

female_non_agg_df = pd.DataFrame({'path': path, 'aggressiveness': aggressiveness, 'gender':gender})
female_non_agg_df.head()

                                                path  aggressiveness  gender
0  Audio Dataset/Female/Non-Aggressive\03-01-01-0...               0       0
1  Audio Dataset/Female/Non-Aggressive\03-01-01-0...               0       0
2  Audio Dataset/Female/Non-Aggressive\03-01-01-0...               0       0
3  Audio Dataset/Female/Non-Aggressive\03-01-01-0...               0       0
4  Audio Dataset/Female/Non-Aggressive\03-01-01-0...               0       0

In [7]:
male_agg_dir_list = os.listdir(male_aggressive_path)
path = []
aggressiveness = []
gender = []
for i in male_agg_dir_list:
    path.append(male_aggressive_path + '\\' + i)
    aggressiveness.append(1)
    gender.append(1)

male_agg_df = pd.DataFrame({'path': path, 'aggressiveness': aggressiveness, 'gender':gender})
male_agg_df.head()

                                                path  aggressiveness  gender
0  Audio Dataset/Male/Aggressive\03-01-05-01-01-0...               1       1
1  Audio Dataset/Male/Aggressive\03-01-05-01-01-0...               1       1
2  Audio Dataset/Male/Aggressive\03-01-05-01-01-0...               1       1
3  Audio Dataset/Male/Aggressive\03-01-05-01-01-0...               1       1
4  Audio Dataset/Male/Aggressive\03-01-05-01-01-0...               1       1

In [8]:
male_non_agg_dir_list = os.listdir(male_non_aggressive_path)
path = []
aggressiveness = []
gender = []
for i in male_non_agg_dir_list:
    path.append(male_non_aggressive_path + '\\' + i)
    aggressiveness.append(0)
    gender.append(1)

male_non_agg_df = pd.DataFrame({'path': path, 'aggressiveness': aggressiveness, 'gender':gender})
male_non_agg_df.head()

                                                path  aggressiveness  gender
0  Audio Dataset/Male/Non-Aggressive\03-01-01-01-...               0       1
1  Audio Dataset/Male/Non-Aggressive\03-01-01-01-...               0       1
2  Audio Dataset/Male/Non-Aggressive\03-01-01-01-...               0       1
3  Audio Dataset/Male/Non-Aggressive\03-01-01-01-...               0       1
4  Audio Dataset/Male/Non-Aggressive\03-01-01-01-...               0       1

In [10]:
# Concatenate all the dataframes
data = pd.concat([female_agg_df,female_non_agg_df,male_agg_df,male_non_agg_df], ignore_index=True, axis=0)

# Save the dataframe to a csv file
data.to_csv('Data\\Audio_Paths.csv', index=False)

data.head()

                                                path  aggressiveness  gender
0  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0
1  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0
2  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0
3  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0
4  Audio Dataset/Female/Aggressive\03-01-05-01-01...               1       0